---
- name: DevOps Server Configuration BSE-8B
  hosts: servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - curl
          - wget
          - git
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull Docker app image
      shell: docker pull areeba280/devops-app:v1

    - name: Run DevOps app container
      shell: |
        docker stop devops-app || true
        docker rm devops-app || true
        docker run -d -p 3000:3001 --name devops-app --restart always areeba280/devops-app:v1

    - name: Verify app is running
      shell: curl -s http://localhost:3000
      register: health_check

    - name: Show result
      debug:
        var: health_check.stdout
